[versions]
agp = "8.13.0"
desugar_jdk_libs_nio = "2.1.5"
fst = "3.0.3"
kotlin = "2.2.0"
coreKtx = "1.17.0"
appcompat = "1.7.1"
biometric = "1.1.0"
new_pipe_extractor = "v0.24.8"
webkit = "1.14.0"
viewpager2 = "1.1.0"
cardview = "1.0.0"
retrofit = "3.0.0"
constraint_layout = "2.2.1"
lifecycleProcess = "2.9.2"
coroutine = "1.10.2"
lottie = "6.6.7"
circleimageview = "3.1.0"
media3player = "1.8.0"
jellyfin_ffmpeg = "1.3.1+2"
mp4_iso_parser = "1.1.22"
okhttp = "5.1.0"
gson = "2.13.1"
jsoup = "1.21.1"
glide = "4.16.0"
permissionx = "1.8.1"
parse = "4.3.0"
storage = "2.2.0"
ytdlp = "0.18.0"
dsljson = "2.0.2"
jsonbind = "1.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }
desugar_jdk_libs_nio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugar_jdk_libs_nio" }
fst = { module = "de.ruedigermoeller:fst", version.ref = "fst" }
kotlin_coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
kotlin_coroutines_core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
constraint_layout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraint_layout" }
media3_exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3player" }
media3_exoplayer_hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3player" }
media3_exoplayer_dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3player" }
media3_session = { module = "androidx.media3:media3-session", version.ref = "media3player" }
media3-datasource = { module = "androidx.media3:media3-datasource", version.ref = "media3player" }
media3_ui = { module = "androidx.media3:media3-ui", version.ref = "media3player" }
jellyfin_ffmpeg = { module = "org.jellyfin.media3:media3-ffmpeg-decoder", version.ref = "jellyfin_ffmpeg" }
mp4_iso_parser = { module = "com.googlecode.mp4parser:isoparser", version.ref = "mp4_iso_parser" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit_converter_gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
parse = { module = "com.github.parse-community.Parse-SDK-Android:parse", version.ref = "parse" }
permissionx = { module = "com.guolindev.permissionx:permissionx", version.ref = "permissionx" }
saf_storage = { module = "com.anggrayudi:storage", version.ref = "storage" }
ytdlp_ffmpeg = { module = "io.github.junkfood02.youtubedl-android:ffmpeg", version.ref = "ytdlp" }
ytdlp_library = { module = "io.github.junkfood02.youtubedl-android:library", version.ref = "ytdlp" }
newpipe_extractor = { module = "com.github.teamnewpipe.NewPipeExtractor:NewPipeExtractor", version.ref = "new_pipe_extractor" }
dsljson = { module = "com.dslplatform:dsl-json", version.ref = "dsljson" }
jsonbind_api = { module = "javax.json.bind:javax.json.bind-api", version.ref = "jsonbind" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt" }
